### ISSUE TITLE
Your client has issued a malformed or illegal request

### ISSUE THREAD

**Issue by davidmigloz** [tazatechnology/pinecone#2]
Hello!

Thank you very much for the client.

I am trying to integrate Pinecone in [LangChain.dart](https://github.com/davidmigloz/langchain_dart) using your client. However, I am always getting the following exception when trying to make any GET request:

```
PineconeClientException({
  "uri": "https://controller.gcp-starter.pinecone.io/databases/langchain-dart",
  "method": "GET",
  "code": 400,
  "message": "Unsuccessful response",
  "body": "\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>400 Bad Request</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Bad Request</h1>\n<h2>Your client has issued a malformed or illegal request.</h2>\n<h2></h2>\n</body></html>\n"
})
```

After debugging it, it seems that it is caused by this line:
https://github.com/tazatechnology/pinecone/blob/d4ee12ebebbbf269cf1684ad32df154b6a947a51/lib/src/generated/client.dart#L206

If the body is null, it is still serializing it as `{}`.

I was going to issue a PR with the fix in [`openapi_spec`](https://pub.dev/packages/openapi_spec), but I saw that you already fixed it in the latest version.

I am trying to regenerate the Pincone client using the latest version, but I am getting some other errors:
```
Failed assertion: line 10405 pos 13: 'values == null || ref == null': Cannot define both values and ref
```

And I'm not sure how to fix them. So I will leave it to you 🙂

Thanks again for your work.

**Comment by walsha2** [comment]
@davidmigloz this should all be resolved as of the [latest release](https://pub.dev/packages/pinecone). I tested the latest dart `pinecone` client on a deployed pinecone DB directly and all of the operations worked as expected.

Let me know if you run into any further issues!

**Comment by davidmigloz** [comment]
How do you run the generator in this package?

If I run the `oas/main.dart`, I still get the following exception:
```
'package:openapi_spec/src/open_api/index.freezed.dart': Failed assertion: line 10433 pos 13: 'values == null || ref == null': Cannot define both values and ref
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      new _$_SchemaEnum (package:openapi_spec/src/open_api/index.freezed.dart:10433:13)
#3      __$$_SchemaEnumCopyWithImpl.call (package:openapi_spec/src/open_api/index.freezed.dart:10382:18)
#4      Schema.dereference.<anonymous closure> (package:openapi_spec/src/open_api/schema.dart:250:46)
#5      _$_SchemaEnum.map (package:openapi_spec/src/open_api/index.freezed.dart:10529:23)
#6      Schema.dereference (package:openapi_spec/src/open_api/schema.dart:222:12)
#7      SchemaGenerator._writeProperty.<anonymous closure> (package:openapi_spec/src/generators/schema.dart:547:15)
```

**Comment by davidmigloz** [comment]
Ahh I missed the `Makefile`. `make generate` works thanks! 
(not sure why it was actually failing before, as I was actually running the same commands but from the IDE)
